todoapp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url(r'^add_list/$', views.add_list, name='add_list'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^(?P<list_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<list_id>[0-9]+)/(?P<task_id>[0-9]+)/complete/$', views.complete, name='complete'),
    url(r'^(?P<list_id>[0-9]+)/(?P<task_id>[0-9]+)/delete/$', views.delete_task, name='delete_task'),
    url(r'^(?P<list_id>[0-9]+)/add_task/$', views.add_task, name='add_task'),
]

todolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('todoapp.urls', namespace="todoapp")),
]

todoapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class TodoList(models.Model):
    list_name = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.list_name


class Task(models.Model):
    task_name = models.CharField(max_length=200)
    description = models.CharField(max_length=500)
    created = models.DateTimeField(default=timezone.now())
    to_be_completed = models.DateField()
    completed = models.BooleanField(default=False)
    todo_list = models.ForeignKey(TodoList, on_delete=models.CASCADE)

    def __str__(self):
        return self.task_name

todoapp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import TodoList, Task


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class TaskForm(forms.ModelForm):
    to_be_completed = forms.DateField(widget=forms.SelectDateWidget())

    class Meta:
        model = Task
        fields = ['task_name', 'description', 'to_be_completed']


class ListForm(forms.ModelForm):

    class Meta:
        model = TodoList
        fields = ['list_name']

todoapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Task, TodoList

from .forms import UserForm, TaskForm, ListForm


class IndexView(generic.ListView):
    template_name = 'todoapp/index.html'
    context_object_name = 'lists'
    paginate_by = 10

    def get_queryset(self):
        if not self.request.user.is_anonymous():
            return TodoList.objects.filter(user=self.request.user).order_by('created')
        else:
            return []


def detail(request, list_id):
    mylist = get_object_or_404(TodoList, pk=list_id)
    mytasks = Task.objects.filter(todo_list=mylist).order_by('created')
    return render(request, 'todoapp/detail.html', {'mylist': mylist, 'tasks': mytasks})


@login_required
def complete(request, list_id, task_id):
    mylist = get_object_or_404(TodoList, pk=list_id)
    mytask = get_object_or_404(Task, pk=task_id)
    mytask.completed = True
    mytask.save()
    mytasks = Task.objects.filter(todo_list=mylist)
    return render(request, 'todoapp/detail.html',  {'mylist': mylist, 'tasks': mytasks})


@login_required
def delete_task(request, list_id, task_id):
    mylist = get_object_or_404(TodoList, pk=list_id)
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    mytasks = Task.objects.filter(todo_list=mylist)
    return HttpResponseRedirect(reverse('todoapp:detail', args=(list_id,)))


@login_required
def add_task(request, list_id):
    form = TaskForm(request.POST or None)
    if form.is_valid():
        mylist = get_object_or_404(TodoList, pk=list_id)
        task = form.save(commit=False)
        task.todo_list = mylist
        task.task_name = form.cleaned_data['task_name']
        task.description = form.cleaned_data['description']
        task.to_be_completed = form.cleaned_data['to_be_completed']
        task.created = timezone.now()
        task.completed = False
        task.save()
        return HttpResponseRedirect(reverse('todoapp:detail', args=(list_id,)))
    return render(request, 'todoapp/add_task.html', {'form': form})


@login_required
def add_list(request):
    form = ListForm(request.POST or None)
    if form.is_valid():
        mylist = form.save(commit=False)
        mylist.user = request.user
        mylist.list_name = form.cleaned_data['list_name']
        mylist.created = timezone.now()
        mylist.save()
        return redirect('/')
    return render(request, 'todoapp/add_task.html', {'form': form})


def signup(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('/')

    form = UserForm()
    return render(request, 'todoapp/signup.html', {'form': form})

todoapp/templates/todoapp/add_task.html
{% extends 'todoapp/base.html' %}

{% block content %}
  <h2>{{ h2title }}</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Save</button>
  </form>
{% endblock %}

todoapp/templates/todoapp/base.html
<! DOCTYPE html>

{% load static %}
<html lang="en">

<html>
    <head>
        <meta charset="utf-8">
        <title> {% block title %}Page Title{% endblock %} </title>
        <link rel="stylesheet" type="text/css" href="{% static 'todoapp/style.css' %}"/>
   </head>

   <body>
        {% if user.is_authenticated %}
            <ul class="nav">
                <li> username: <strong><font color="red">{{ user.username }} </font></strong></li>
                <li><a href="{% url 'todoapp:index' %}">Home</a></li>
                <li><a href="{% url 'todoapp:logout' %}">Log Out</a></li>
            </ul>
        {% else %}
            <ul class="nav">
                <li><a href="{% url 'todoapp:index' %}">Home</a></li>
                <li><a href="{% url 'todoapp:login' %}">Log In</a></li>
                <li><a href="{% url 'todoapp:signup' %}">Sign Up</a></li>
            </ul>
        {% endif %}

        {% block content %}
        {% endblock %}

   </body>
</html>

todoapp/templates/todoapp/detail.html
{% extends 'todoapp/base.html' %}




{% block content %}

<style>
.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button_add{
    background-color: blue;
    border: none;
}

.due{
    color:green;
}
</style>
{% load todoapp_filters %}
{% if mylist %}
    <div style="text-align:center"><strong>{{mylist.list_name}}  -- created at {{mylist.created}}</strong></div>
    {% if tasks %}
        {% for task in tasks %}
            <div id="main">
                <div style="text-align:center;border:1px solid green">
                    <p><strong>{{task.task_name}}</strong></p>
                    <p><strong>{{task.description}}</strong></p>
                    {% if task.completed %}
                    <p><strong><font color="green">This task was completed</font></strong></p>
                    {% else %}
                    <p><strong><font color="red">Task is incomplete</font></strong></p>
                        <div class='due_date'>
                     <b class="due">{{ task.to_be_completed|get_due_date_string }}</b>
                    </div>
                    {% endif %}
                    <p>started at {{task.created}}</p>
                    <p>due date {{task.to_be_completed}}</p>
                </div>
                <div style="text-align:center">
                    <a href="{% url 'todoapp:complete' mylist.id task.id %}" class="button">Complete</a>
                    <a href="{% url 'todoapp:delete_task' mylist.id task.id %}" class="button">Delete</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
<div style="text-align:center"><a href="{% url 'todoapp:add_task' mylist.id %}" class="button button_add">Add task</a></div>


{% endif %}

{% endblock %}

todoapp/templates/todoapp/index.html

{% extends 'todoapp/base.html' %}


{% block title %}
Task list
{% endblock %}

{% block content %}

<style>
    .tasks {
    list-style-type: none;

    padding: 20px 0 20px 0;
}

.tasks>li>a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

.tasks>li {
    text-align: center;
    display: block;
    padding: 0 25px 0 25px
}


.tasks>li:last-child {
    border-bottom: none;
}

.tasks >li>a.active {
    background-color: green;
    color: white;
}

.tasks >li>a:hover:not(.active) {
    background-color: #555;
    color: white;
}

.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
}

.button_add{
    background-color: blue;
    border: none;
}
</style>


{% if lists%}
    <ul class="tasks">
        {% for list in lists %}
        <li>
            <a href="{% url 'todoapp:detail' list.id %}">
                <div><strong>{{ list.list_name }}</strong></div>
                <div><strong>created on {{list.created}}</strong></div>
            </a>
        </li>
        {% endfor %}
    </ul>
    <div style="text-align:center"><a href="{% url 'todoapp:add_list'%}" class="button button_add">Add list</a></div>
    {% include 'todoapp/pagination.html' %}
{% else %}
    <h3 align="center"><font color="blue">No tasks to show. Please login or signup</font></h3>

{% endif %}

{% endblock %}

todoapp/templates/todoapp/pagination.html
{% if is_paginated %}

<style>
    .pagination {
        list-style-type: none;
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #333;
    }

    .pagination > li {
    float: left
    }
   .pagination > li a {
        display: block;
        color: blue;
        padding: 8px 16px;
        text-decoration: none;
    }

    .pagination > li a {
        text-align: center;
    }

    .pagination > li  a:hover:not(.active) {
        background-color: #555;
        color: white;
    }
</style>

  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a href="?page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>

      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
          <a href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}
         {% if page_obj.has_next %}
        <li>
          <a href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

todoapp/templates/todoapp/signup.html
{% extends 'todoapp/base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}